POST http://localhost:7000/bid
content-type:application/json

{
    "orderNo":"123456",
    "transporterId": "620a435e9961e847c6ee96c9",
    "bidAmount": 700
}

###
GET http://localhost:7000/bid/specific?transporterUserName=shreali&orderNo=99&userName=missula

###
GET http://localhost:7000/bid?userName=pujamatta&orderNo=10
###
PATCH http://localhost:7000/bid/
content-type: application/json

{
    "orderNo":"99",
    "userName": "shreali",
    "bidAmount": 1500
}

###
DELETE http://localhost:7000/bid?orderNo=123456&transporterId=620a435e9961e847c6ee96c2

###

GET http://localhost:7000/bid/history?userName=shreali

###
GET http://localhost:7000/bid/suitablebids?userName=shreali