
///client signup

###
POST http://localhost:7000/users/client/signup
content-Type: application/json

{
    "firstName": "Monkey",
    "lastName": "Luffy",
    "middleName": "D.",
    "userName": "pirateking",
    "password": "user123",
    "email": "pirateking@gmail.com",
    "contactNo": [9856213471, 9856523471],
    "address": "Windmill Village",
    "photo": "East Blue"
}


///client login

###
POST http://localhost:7000/users/client
content-Type: application/json

{
   "email": "piratekingg@gmail.com",
   "password": "user12345"
}

///client update

### 
PATCH http://localhost:7000/users/client
content-Type: application/json

{
    "email":"pirateking@gmail.com",
    "password":"user123"
}

///client delete

###
DELETE http://localhost:7000/users/client?email=pirateking@gmail.com

###
GET http://localhost:7000/users/client/details?userName=pujamatta