POST http://localhost:7000/users/ratingandreview?userType=transporter
content-Type: application/json

{
    "rating" : 4.5,
    "review" : "this is review test",
    "userNameReviewer": "hb",
    "userNameReviewed": "pirateking"
}

###
GET http://localhost:7000/users/ratingandreview?userType=client&userName=pirateking

###
POST http://localhost:7000/users/inAppCurrency?userType=transporter
content-type: application/json

{
    "userName":"hb",
    "inAppCurrency":100
}

###
GET http://localhost:7000/users/transporter/details?userName=hb