//get all orders of different status
###
GET http://localhost:7000/order/history?orderStatus=onbid&userName=pirateking

//create new order
###
POST http://localhost:7000/order/
content-type : application/json

 {
    "userName": "pirateQueen",
    "orderStatus": "prebid",
    "timeFrame": {
      "start": "2022-05-10T12:00:55Z",
      "end": "2022-05-12T00:00:00Z"
    },
    "startPoint": ["locations 10", 27.661105220208288, 85.5036324206804],
    "destination": ["locations 9", 27.699120372256214, 85.37631882790146],
    "distance": 2584,
    "biddingTime": {
      "start": "2022-05-07T00:00:00Z",
      "end": "2022-05-08T22:11:19Z"
    },
    "maxBudget": 2342,
    "shipments": ["Tomatoes - Diced, Canned"],
    "shipmentCount": [3],
    "shipmentPhoto": "https://firebasestorage.googleapis.com/v0/b/saman-pathao-57245.appspot.com/o/orderimage%2F2.jpg?alt=media&token=ac0ff7a5-cfe0-41ee-9ab8-b71ff815788a",
    "shipmentWeight": 30,
    "shipmentDimension": { "length": [4], "width": [1], "height": [1] },
    "fragile": true,
    "minRated": 1
  }



//get any specific order by their orderNo
###
GET http://localhost:7000/order?userName=pirateking&orderNo=38


//update order
###
PATCH  http://localhost:7000/order
content-type : application/json

{
    "userName": "pirateking",
    "orderNo":"38",
    "biddingTime":{
        "start":"2022-05-06 17:33",
        "end":"2022-05-06 17:59"
    },
    "maxBudget":3000,
    "fragile":false,
    "orderStatus":"prebid"
}

//scheduler calls this api
###

PATCH  http://localhost:7000/order/statusChanger
content-type : application/json

{
    "userName": "pujamatta",
    "orderNo":"1",
    "biddingTime":{
        "start":"2022-02-21 15:10",
        "end":"2020-02-21 16:40"
    },
    "oldOrderStatus":"prebid",
    "fragile":false
}

###
DELETE http://localhost:7000/order/
content-type: application/json

{
    "userName":"pirateking",
    "orderNo":"38"
}

###
GET http://localhost:7000/order/history?orderStatus=onbid&userType=transporter&rating=5&lat=27.675795&long=85.3710583

###
GET http://localhost:7000/order/orderedBy?orderNo=38