GET http://localhost:7000/order/history?userName=pirateking

###
POST http://localhost:7000/order/
content-type : application/json

{
    "userName": "pirateking",
    "orderNo":"111337",
    "orderStatus":"postbid",
    "timeFrame":{
        "start":"2020-10-10 10:10",
        "end":"2020-10-10 10:20"
    },
    "startPoint":["kathmanud",10,10],
    "destination":["kathmanud",10,10],
    "distance":10,
    "biddingTime":{
        "start":"2020-10-10 09:10",
        "end":"2020-10-10 09:15"
    },
    "maxBudget":200,
    "shipments":["shipments1","shipments2"],
    "shipmentWeight":50.5,
    "shipmentDimension":{
        "length":[10,20],
        "width":[10,20],
        "height":[10,20]
    },
    "fragile":false,
    "minRated":3
}

###
GET http://localhost:7000/order?userName=pirateking&&id=620cacbe9ad985d1b9902c93

###
PATCH  http://localhost:7000/order
content-type : application/json

{
    "id":"620cacbe9ad985d1b9902c93",
    "userName": "pirateking",
    "orderNo":"123456",
    "orderStatus":"postbid",
    "timeFrame":{
        "start":"2020-10-10 10:10",
        "end":"2020-10-10 10:20"
    },
    "startPoint":["Bhaktapur",10,10],
    "destination":["Bhaktapur",10,10],
    "distance":10,
    "biddingTime":{
        "start":"2020-10-10 09:10",
        "end":"2020-10-10 09:15"
    },
    "maxBudget":200,
    "shipments":["shipments1","shipments2"],
    "shipmentWeight":50.5,
    "shipmentDimension":{
        "length":[10,20],
        "width":[10,20],
        "height":[10,20]
    },
    "fragile":false,
    "minRated":3
}