
POST http://localhost:7000/users/transporter/signup
content-Type: application/json

{"firstName":"Junu","lastName":"Himanshu","email":"junushu@gmail.com","password":"IlIoWc","contactNo":"041-66772","address":"Ghorahi","photo":"https://picsum.photos/200/300"}

###
POST http://localhost:7000/users/transporter
content-Type: application/json

{
    "email": "junushu@gmail.com",
    "password": "user123"
}

###
//userdetails change
### 
PATCH http://localhost:7000/users/transporter
content-Type: application/json

{
    "userName":"junushu",
    "firstName": "Monkey",
    "lastName": "lucy",
    "middleName": "D."
}

###
//password change
###
PATCH http://localhost:7000/users/transporter
content-Type: application/json

{
    "userName":"junushu",
    "oldPassword": "IlIoWc",
    "newPassword": "user123"
}
###

###
DELETE http://localhost:7000/users/transporter?email=junushu@gmail.com

###
GET http://localhost:7000/users/transporter/details?userName=junushu