final orders = [
  {
    'orderNo': '1',
    'photo':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYfV3y6k3rHxXC2fjB3r_5H1yGvlPKM9njYQ&usqp=CAU',
    'bids': [10, 20, 2000, 300],
    'biddingTime': {'startTime': '12:30', 'endTime': '1:30'},
    'maxBudget': '5000',
    'orderStatus': 'onbid',
    'timeFrame': {'startTime': '9:00', 'endTime': '4:30'},
    'startPoint': 'Gatthaghar',
    'destination': 'Gokarna',
    'weight': '',
    'distance': '20',
    'fragile': 'true',
  },
  {
    'orderNo': '12',
    'photo':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYfV3y6k3rHxXC2fjB3r_5H1yGvlPKM9njYQ&usqp=CAU',
    'bids': [10, 20, 2000, 300],
    'biddingTime': {'startTime': '12:30', 'endTime': '1:30'},
    'maxBudget': '5000',
    'orderStatus': 'onbid',
    'timeFrame': {'startTime': '9:00', 'endTime': '4:30'},
    'startPoint': 'Gatthaghar',
    'destination': 'Gokarna',
    'weight': '',
    'distance': '20',
    'fragile': 'true',
  },
  {
    'orderNo': '123',
    'photo':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYfV3y6k3rHxXC2fjB3r_5H1yGvlPKM9njYQ&usqp=CAU',
    'bids': [10, 20, 2000, 300],
    'biddingTime': {'startTime': '12:30', 'endTime': '1:30'},
    'maxBudget': '5000',
    'orderStatus': 'onbid',
    'timeFrame': {'startTime': '9:00', 'endTime': '4:30'},
    'startPoint': 'Gatthaghar',
    'destination': 'Gokarna',
    'weight': '',
    'distance': '20',
    'fragile': 'true',
  },
  {
    'orderNo': '1234',
    'photo':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYfV3y6k3rHxXC2fjB3r_5H1yGvlPKM9njYQ&usqp=CAU',
    'bids': [10, 20, 2000, 300],
    'biddingTime': {'startTime': '12:30', 'endTime': '1:30'},
    'maxBudget': '5000',
    'orderStatus': 'onbid',
    'timeFrame': {'startTime': '9:00', 'endTime': '4:30'},
    'startPoint': 'Gatthaghar',
    'destination': 'Gokarna',
    'weight': '',
    'distance': '20',
    'fragile': 'true',
  },
  {
    'orderNo': '12345',
    'photo':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYfV3y6k3rHxXC2fjB3r_5H1yGvlPKM9njYQ&usqp=CAU',
    'bids': [10, 20, 2000, 300],
    'biddingTime': {'startTime': '12:30', 'endTime': '1:30'},
    'maxBudget': '5000',
    'orderStatus': 'onbid',
    'timeFrame': {'startTime': '9:00', 'endTime': '4:30'},
    'startPoint': 'Gatthaghar',
    'destination': 'Gokarna',
    'weight': '',
    'distance': '20',
    'fragile': 'true',
  },
];
